In [16]:
import numpy as np
import math
import time

# Vectorized vs Non- Vectorized

In [34]:
v = np.random.random(1000000)
tic = time.time()
u = np.zeros((1000000,1))
for i in range(1000000):
    u[i] = math.exp(v[i])
toc = time.time()
print(u)
print("non_vectorized version" + str(1000*(toc-tic)) + "ms")

[[1.36160416]
 [1.65776487]
 [1.19300042]
 ...
 [1.75626029]
 [1.29424128]
 [1.94647773]]
non_vectorized version761.1944675445557ms


In [35]:
tic1 = time.time()
w = np.exp(v)
print(w)
toc1 = time.time()
print("vectorized version" + str(1000*(toc1-tic1)) + "ms")

[1.36160416 1.65776487 1.19300042 ... 1.75626029 1.29424128 1.94647773]
vectorized version8.99505615234375ms


# Aggregate functions

In [36]:
np.log(v)

array([-1.17550349, -0.68226613, -1.73459592, ..., -0.57414407,
       -1.35508784, -0.40643341])

In [37]:
v

array([0.30866353, 0.50547023, 0.17647149, ..., 0.56318671, 0.25792464,
       0.66602145])

In [38]:
np.abs(v)

array([0.30866353, 0.50547023, 0.17647149, ..., 0.56318671, 0.25792464,
       0.66602145])

In [39]:
np.max(v)

0.9999994301317567

In [40]:
v**2

array([0.09527318, 0.25550016, 0.03114219, ..., 0.31717927, 0.06652512,
       0.44358457])

In [41]:
1/v

array([3.23977374, 1.97835587, 5.66663755, ..., 1.77561008, 3.87710149,
       1.50145315])

# broadcasting

In [58]:
A= np.array([[56.0, 0.0, 4.4, 68.0],
    [1.20, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]])

print(A)
    

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [59]:
cal = A.sum(axis=0)
print(cal)
type(cal)

[ 59.  239.  155.4  76.9]


numpy.ndarray

In [50]:
b=cal.reshape(1,4)
print(b)
type(b)

[[ 59.  239.  155.4  76.9]]


numpy.ndarray

In [60]:
percentage = (A/cal)*100
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [118]:
e = np.arange(5).reshape(5,1)
e

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [119]:
e + 100

array([[100],
       [101],
       [102],
       [103],
       [104]])

In [121]:
t = np.arange(6).reshape(2,3)
t

array([[0, 1, 2],
       [3, 4, 5]])

In [122]:
f = np.array([100, 200, 300])
f

array([100, 200, 300])

In [123]:
yy = t+f
yy

array([[100, 201, 302],
       [103, 204, 305]])

In [ ]:
# so what brodacasting does is, that if you have any matrix A with a shape of (m*n)  
# and if you want to add or divide or do any other mathematics operations into it with a matrix B of shape (1*n),
# then it will made duplicate B matrix OF SHAPE m*n and then apply these above opeartions.

# np.rehsape : it allows to change the shape of the matrix

In [64]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
print(z)
print(" shape of z :", z.shape )


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 shape of z : (3, 4)


In [65]:
np.reshape(z, (6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [67]:
np.reshape(z,(12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
# here -1 simply means that it is an unknown dimension and we want numpy to figure it out. 
# And numpy will figure this by looking at the 'length of the array and remaining dimensions' 
# and making sure it satisfies the above mentioned criteria of 12 elements(3*4)

In [68]:
z.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
z.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# np.ravel : 
### It is equivalent to reshape(-1, order=order) If you try to modify the flattened view then you end up with that same change in the original array.	

In [71]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.ravel(x) #default order is C :  IT FOLLOWS THE INDEXING OF COLUMS AND THE EACH ROWS

array([1, 2, 3, 4, 5, 6])

In [73]:
np.ravel(x, order='F') # IT FOLLOWS THE INDEXING OF ROWS(11, 12)

array([1, 4, 2, 5, 3, 6])

In [76]:
a = np.arange(8)[::-1] #descending format
a

array([7, 6, 5, 4, 3, 2, 1, 0])

In [80]:
np.ravel(a)

array([7, 6, 5, 4, 3, 2, 1, 0])

# np.flatten : 

#### it also flatten the way ravel did but Changes made to flattened array is not reflected back to the original array.

In [81]:
n = np.array([[1,2], [3,4]])
n

array([[1, 2],
       [3, 4]])

In [82]:
n.flatten() # temporary flattened


array([1, 2, 3, 4])

In [83]:
n # see n still remained the same

array([[1, 2],
       [3, 4]])

# np.flat

In [84]:
m = np.arange(1, 7).reshape(2, 3)
m

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
for i in m: # we had combined two arrays to make one matrix of shape(2,3), thast what we have tried to show here.
    print(i)

[1 2 3]
[4 5 6]


In [96]:
# but what if we want to flattened in to one array
o = np.arange(1, 10).reshape(3, 3)
for item in o.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [107]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
np.array([[1, 2], [3, 4], [5, 6]]).flat[3:6]

array([4, 5, 6])

In [105]:
np.array([[1], [2], [3], [4], [5]]).flat[0:5]

array([1, 2, 3, 4, 5])